####################################
FROM ubuntu_xrdp_en:24.04_base

# RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
      zsh htop tmux vim net-tools iproute2 wget curl 

# Set locale to English en_US.UTF-8
RUN locale-gen en_US.UTF-8 \
    && echo 'LC_ALL=en_US.UTF-8' > /etc/default/locale \
    && echo 'LANG=en_US.UTF-8' >> /etc/default/locale
ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8
# Set default vars
ENV DEFAULT_USER=developer \
    DEFAULT_PASSWD=xrdppasswd
# Set sudoers for any user
RUN echo "ALL ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/ALL
# Change permission so that non-root user can add users and groups
RUN chmod u+s /usr/sbin/useradd \
    && chmod u+s /usr/sbin/groupadd

# Expose RDP port
# EXPOSE 3389
# change expose RDP port to 43389
RUN sed -i 's/3389/43389/g' /etc/xrdp/xrdp.ini
EXPOSE 43389

# Setup
RUN { \
        echo 'if [[ -d /run/user/$(id -u) ]]; then'; \
        echo '  export XDG_RUNTIME_DIR=/run/user/$(id -u)'; \
        echo 'fi'; \
        echo 'exec dbus-run-session -- startlxqt'; \
    } > /etc/skel/.xsession \
    && install -o root -g xrdp -m 2775 -d /var/run/xrdp \
    && install -o root -g xrdp -m 3777 -d /var/run/xrdp/sockdir \
    && install -o root -g root -m 0755 -d /var/run/dbus \
    && install -o root -g root -m 0644 /dev/null /etc/securetty \
    && usermod -aG ssl-cert xrdp
# Disable unavailable features
RUN sed -i 's|.*pam_systemd.so|#&|g' /etc/pam.d/common-session \
    && sed -i.org 's/plugins=.*/plugins=mainmenu, showdesktop, desktopswitch, quicklaunch, taskbar, tray, statusnotifier/' /etc/xdg/lxqt/panel.conf \
    && mv /etc/xdg/autostart/lxqt-powermanagement.desktop /etc/xdg/autostart/lxqt-powermanagement.desktop.disabled
# Set supervisord conf for xrdp service
RUN { \
        echo "[supervisord]"; \
        echo "user=root"; \
        echo "nodaemon=true"; \
        echo "logfile=/var/log/supervisor/supervisord.log"; \
        echo "childlogdir=/var/log/supervisor"; \
        echo "[program:dbus]"; \
        echo "command=/usr/bin/dbus-daemon --system --nofork --nopidfile"; \
        echo "[program:xrdp-sesman]"; \
        echo "command=/usr/sbin/xrdp-sesman --nodaemon"; \
        echo "[program:xrdp]"; \
        echo "command=/usr/sbin/xrdp --nodaemon"; \
        echo "user=xrdp"; \
    } > /etc/supervisor/xrdp.conf
# Copy entrypoint script
COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT ["docker-entrypoint.sh"]
