####################################
FROM ubuntu:24.04_xrdp_en
# For slim:
#   --build-arg ADDITIONAL_APT_GET_OPTS=--no-install-recommends

# RUN apt-get update
RUN echo 'path-include=/usr/share/locale/ru/LC_MESSAGES/*.mo' > /etc/dpkg/dpkg.cfg.d/includes \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      fonts-noto-cjk \
      ibus \
      ibus-gtk \
      ibus-gtk3 \
      ibus-gtk4 \
      im-config \
      ibus-table-wubi \
      ibus-pinyin \
      language-pack-zh-hans \
      language-pack-zh-hans-base

# Set locale ru timezone Moscow
RUN cp /usr/share/zoneinfo/Europe/Moscow /etc/localtime \
    && echo 'Europe/Moscow' > /etc/timezone
RUN locale-gen ru_RU.UTF-8 \
    && echo 'LC_ALL=ru_RU.UTF-8' > /etc/default/locale \
    && echo 'LANG=ru_RU.UTF-8' >> /etc/default/locale
ENV LANG=ru_RU.UTF-8 \
    LANGUAGE=ru_RU:ru \
    LC_ALL=ru_RU.UTF-8