####################################
FROM ubuntu_xrdp_en:24.04
# For slim:
#   --build-arg ADDITIONAL_APT_GET_OPTS=--no-install-recommends

# RUN apt-get update
RUN echo 'path-include=/usr/share/locale/zh_CN/LC_MESSAGES/*.mo' > /etc/dpkg/dpkg.cfg.d/includes \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      fonts-noto-cjk \
      ibus \
      ibus-gtk \
      ibus-gtk3 \
      ibus-gtk4 \
      im-config \
      ibus-table-wubi \
      ibus-pinyin \
      language-pack-zh-hans \
      language-pack-zh-hans-base
      
# Set locale & timezone 上海时区 Asia/Shanghai
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo 'Asia/Shanghai' > /etc/timezone
RUN locale-gen zh_CN.UTF-8 \
    && echo 'LC_ALL=zh_CN.UTF-8' > /etc/default/locale \
    && echo 'LANG=zh_CN.UTF-8' >> /etc/default/locale
ENV LANG=zh_CN.UTF-8 \
    LANGUAGE=zh_CN:zh \
    LC_ALL=zh_CN.UTF-8

