name: Publish Docker image vnc/ubuntu20.04_slim

on: [workflow_dispatch, workflow_call]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: vnc
          file: vnc/Dockerfile.ubuntu20.04
          platforms: linux/amd64,linux/arm64
          build-args: |
            ADDITIONAL_APT_GET_OPTS=--no-install-recommends
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/docker-ubuntu-lxde:20.04-vnc-slim
            ${{ secrets.DOCKERHUB_USERNAME }}/docker-ubuntu-lxde:focal-vnc-slim
